# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schilderij',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschrijving', models.TextField()),
                ('image', models.ImageField(upload_to='img')),
            ],
        ),
    ]
