# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photomgr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schilderij',
            name='formaat',
            field=models.TextField(default='120cm x 80cm'),
            preserve_default=False,
        ),
    ]
